### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**
also contains https://github.com/theforeman/puppet-certs/pull/411

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
CI needs to be updated to run on Puppet 8.

**Review by ekohl — CHANGES_REQUESTED** [review]
Please rebase

**Comment by bastelfreak** [comment]
@ekohl rebased

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Argh, auto-merge was enabled but it failed ...

**Comment by ekohl** [comment]
Let's see if https://github.com/theforeman/puppet-certs/pull/438 can resolve those issues.

**Pull request merged**
