### PR TITLE
Fixes #26180 Move type common module to PuppetX namespace so doesn't break 'puppet generate types'

### LINKED ISSUE #247: This module breaks `puppet generate types`
The use of `certs_common` in `types` directory breaks type generation because it's not actually a valid type.

```
# /opt/puppetlabs/bin/puppet generate types --environment production --trace --debug
<SNIP>
Debug: Skipping '/etc/puppetlabs/code/environments/production/modules/certs/lib/puppet/type/ca.rb' because it is up-to-date.
Debug: Skipping '/etc/puppetlabs/code/environments/production/modules/certs/lib/puppet/type/cert.rb' because it is up-to-date.
Debug: Skipping '/etc/puppetlabs/code/environments/production/modules/certs/lib/puppet/type/certs_bootstrap_rpm.rb' because it is up-to-date.
Debug: Loading custom type 'certs_common' in '/etc/puppetlabs/code/environments/production/modules/certs/lib/puppet/type/certs_common.rb'.
Error: undefined method `[]' for nil:NilClass
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/generate/type.rb:198:in `block in generate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/generate/type.rb:174:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/generate/type.rb:174:in `generate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/face/generate.rb:60:in `block (3 levels) in <top (required)>'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/interface/action.rb+eval[wrapper]:264:in `types'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/face_base.rb:247:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:383:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:667:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:135:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:73:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Error: Try 'puppet help generate types' for usage
```

### PR DESCRIPTION
**Pull request by treydock**
Fixes GH-247

Are updates still be done to 4.x versions?  I can re-target against master if not.  I am on Satellite 6.4 which uses 4.2.0 of this module.

### CODE REVIEW

**Comment by ekohl** [comment]
I'm not sure if this will make it into 6.4 since using the modules outside of the installer isn't officially supported. However, we do have a 4.4-stable branch for Katello 3.9/3.10 which is still supported. I'd accept the change there.

The PR processor isn't happy because we use `#xxx` for Redmine issues. In this case you want to use GH-247.

**Comment by treydock** [comment]
@ekohl I am only using the `certs::puppet` class in Puppet because I don't have the installer touching Puppet because I didn't want to have to duplicate all my Hiera data into my answer files which are managed by Puppet.  I have a lot of capsules so installer execution of satellite-installer is handled by Puppet for my capsules.

My hack is pure laziness, I have a lot of Hiera data for the `puppet` module and also define the capsule answer file in Hiera and didn't want to have to duplicate all the data so I just do `puppet: false` for capsules and continued to use `puppet` module outside the installer.  Not necessarily something I need support for since there is a viable alternative, albeit not very DRY.

**Comment by ekohl** [comment]
I very much like the use case and encourage upstream users to do it. Sadly, supporting something downstream can be a bit more tricky. Cherry picks for unsupported features are hard, but customer cases do help set the priority.

Let's get this merged first and cherry picked so it makes it into future versions first :)

**Comment by ekohl** [comment]
Merged in 41a17556ffba4b977da1a68651290d9c96f4b65d

**Pull request closed without merging**
