### PR TITLE
Release 12.0.0

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
I would like to get https://github.com/theforeman/puppet-certs/pull/320 in before we release. That reminds me to get back to it.

**Comment by ehelms** [comment]
This can now be updated with the merge of #320

**Comment by ehelms** [comment]
If this gets updated to include #320 note the following issue -- https://github.com/theforeman/puppet-certs/pull/323

**Comment by wbclark** [comment]
Updated date to April 26th, included #320 , and also added #323 under a new "Issues:" heading.

(Would "New Issues" be more appropriate, to avoid giving the false impression that this is something we've fixed?)

**Comment by ehelms** [comment]
Before we merge and release this, should we bump the version allowed by puppet-katello (e.g. https://github.com/theforeman/puppet-katello/blob/master/metadata.json#L29) and puppet-foreman_proxy_content to reduce the installer breakage cycle and help nightlies ?

**Comment by wbclark** [comment]
> Before we merge and release this, should we bump the version allowed by puppet-katello (e.g. https://github.com/theforeman/puppet-katello/blob/master/metadata.json#L29) and puppet-foreman_proxy_content to reduce the installer breakage cycle and help nightlies ?

Sure, I will open PRs for this.

**Comment by wbclark** [comment]
Opened https://github.com/theforeman/puppet-katello/pull/408 and https://github.com/theforeman/puppet-foreman_proxy_content/pull/348

**Comment by ehelms** [comment]
Could you rebase this PR to ensure there are no further issues with the master branch?

**Comment by wbclark** [comment]
Rebased and updated changelogs

**Review by ehelms — APPROVED** [review]

**Pull request merged**
