### PR TITLE
Refs #35005: Drop certs::pulp_client

### PR DESCRIPTION
**Pull request by ehelms**
These certificates were used to communicate with a Pulp 2 instance
and subsequently Pulp 3 without client authentication support. Client
authentication support was added in Foreman 3.0 and now Foreman
client ceritificates are used to communicate with Pulp 3. These
certificates are no longer needed or used.

### CODE REVIEW

**Comment by ehelms** [comment]
Needs https://github.com/theforeman/puppet-katello/pull/450 to go in first

**Review by chris1984 — APPROVED** [review]
Have merge access on this guy too, so can review. ACK

**Comment by ehelms** [comment]
Will wait on https://github.com/theforeman/puppet-katello_devel/pull/279 before merging

**Comment by chris1984** [comment]
Merge away sir :beers:

**Comment by evgeni** [comment]
This is still used in `puppet-foreman_proxy_content`:
https://github.com/theforeman/puppet-foreman_proxy_content/blob/8b483a3dfcf3b22c6ebfff5a1965d746809d5cc0/manifests/init.pp#L300-L308

(and broke nightly ;))

**Pull request merged**
