### PR TITLE
Add a Rubocop config

### PR DESCRIPTION
**Pull request by ekohl**
This is still a draft because there's some issues with this.

### CODE REVIEW

**Comment by ehelms** [comment]
Are the puppet file changes from Rubocop?

**Comment by ekohl** [comment]
Depends, see the individual commit message.

**Comment by ehelms** [comment]
Ahh you have puppet-lint and Rubocop fixes combined here that makes more sense.

**Comment by ekohl** [comment]
Yes, it's part of voxpupuli-test 2.x. This was a bit of a test to see what kind of changes it would bring. I can see about first upgrading to 2.x without Rubocop.

**Comment by ekohl** [comment]
Closing for now.

**Pull request closed without merging**
