### PR TITLE
allow newer versions of dependencies

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ehelms** [comment]
Needs a stdlib update maybe?

**Comment by mmoll** [comment]
This needs a new puppet-trusted_ca release.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-trusted_ca/releases/tag/v3.0.0 is being released by Travis now.

**Comment by mmoll** [comment]
now this would need a test-rekick ;)

**Pull request merged**
